import BigNumber from 'bignumber.js'


export const ERROR = 'ERROR'


// #SNACKBAR
export const SNACKBAR_ERROR = 'SNACKBAR_ERROR'
export const SNACKBAR_TRANSACTION_HASH = 'SNACKBAR_TRANSACTION_HASH'
export const SNACKBAR_TRANSACTION_RECEIPT = 'SNACKBAR_TRANSACTION_RECEIPT'
export const SNACKBAR_TRANSACTION_CONFIRMED = 'SNACKBAR_TRANSACTION_CONFIRMED'
export const SNACKBAR_MESSAGE = 'SNACKBAR_MESSAGE'


// #Accounts
export const CONNECTION_CONNECTED = 'CONNECTION_CONNECTED'
export const CONNECTION_DISCONNECTED = 'CONNECTION_DISCONNECTED'

export const GET_BALANCES = 'GET_BALANCES'
export const BALANCES_RETURNED = 'BALANCES_RETURNED'


// #Liquidity
export const GET_DEPOSIT_AMOUNT = 'GET_DEPOSIT_AMOUNT'
export const DEPOSIT_AMOUNT_RETURNED = 'DEPOSIT_AMOUNT_RETURNED'

export const GET_WITHDRAW_AMOUNT = 'GET_WITHDRAW_AMOUNT'
export const WITHDRAW_AMOUNT_RETURNED = 'WITHDRAW_AMOUNT_RETURNED'

export const DEPOSIT = 'DEPOSIT'
export const DEPOSIT_RETURNED = 'DEPOSIT_RETURNED'

export const WITHDRAW = 'WITHDRAW'
export const WITHDRAW_RETURNED = 'WITHDRAW_RETURNED'

export const DEPOSIT_ALL = 'DEPOSIT_ALL'
export const DEPOSIT_ALL_RETURNED = 'DEPOSIT_ALL_RETURNED'

export const WITHDRAW_ALL = 'WITHDRAW_ALL'
export const WITHDRAW_ALL_RETURNED = 'WITHDRAW_ALL_RETURNED'

export const STAKE = 'STAKE'
export const STAKE_RETURNED = 'STAKE_RETURNED'

export const UNSTAKE = 'UNSTAKE'
export const UNSTAKE_RETURNED = 'UNSTAKE_RETURNED'


// #lending
export const GET_BORROW_AMOUNT = 'GET_BORROW_AMOUNT'
export const BORROW_AMOUNT_RETURNED = 'BORROW_AMOUNT_RETURNED'

export const GET_REPAY_AMOUNT = 'GET_REPAY_AMOUNT'
export const REPAY_AMOUNT_RETURNED = 'REPAY_AMOUNT_RETURNED'

export const BORROW = 'BORROW'
export const BORROW_RETURNED = 'BORROW_RETURNED'

export const REPAY = 'REPAY'
export const REPAY_RETURNED = 'REPAY_RETURNED'

export const CLAIM = 'CLAIM'
export const CLAIM_RETURNED = 'CLAIM_RETURNED'



// #GENERAL
export const MAX_UINT256 = new BigNumber(2)
  .pow(256)
  .minus(1)
  .toFixed(0);
